mock_opp_one = {'data': {'link': {'href': 'test.com',
   'additionalInfo': {'content': 'description'}},
  'type': 'p',
  'award': {'awardee': {'location': {}},
   'fairOpportunity': {},
   'justificationAuthority': {}},
  'naics': [{'code': ['123'], 'type': 'primary'}],
  'title': 'test',
  'archive': {'date': '2019-10-09', 'type': 'autocustom'},
  'permissions': {'IVL': {'read': False,
    'create': False,
    'delete': False,
    'update': False}},
  'descriptions': [],
  'solicitation': {'deadlines': {'response': '2019-10-08T23:59:59-04:00',
    'responseTz': 'America/New_York'}},
  'organizationId': '100176853',
  'pointOfContact': [{'type': 'primary',
    'email': 'test@test.gov',
    'fullName': 'Name',
    'additionalInfo': {'content': 'Description mail'}}],
  'classificationCode': 'test',
  'placeOfPerformance': {'zip': '20170',
   'country': {'code': 'USA', 'name': 'UNITED STATES'},
   'streetAddress': 'Alton Sq'},
  'solicitationNumber': 'test',
  'additionalReporting': ['none'],
  'organizationLocationId': '50175943'},
 'additionalInfo': {'sections': [{'id': 'header', 'status': 'updated'},
   {'id': 'award', 'status': 'updated'},
   {'id': 'general', 'status': 'updated'},
   {'id': 'classification', 'status': 'updated'},
   {'id': 'description', 'status': 'updated'},
   {'id': 'attachments-links', 'status': 'updated'},
   {'id': 'contact', 'status': 'updated'}]},
 'parent': {},
 'related': {},
 'status': {'code': 'published', 'value': 'Published'},
 'archived': False,
 'cancelled': False,
 'latest': True,
 'deleted': False,
 'postedDate': '2019-09-25T21:43:03.675+0000',
 'modifiedDate': 'modDate',
 'createdDate': '2019-09-25T21:42:23.210+0000',
 'modifiedBy': '',
 'createdBy': '',
 'opportunityId': 'test'}

mock_opp_two = {'data': {'link': {'href': 'testy.com',
   'additionalInfo': {'content': 'description'}},
  'type': 'p',
  'award': {'awardee': {'location': {}},
   'fairOpportunity': {},
   'justificationAuthority': {}},
  'naics': [{'code': ['123'], 'type': 'primary'}],
  'title': 'testy',
  'archive': {'date': '2019-10-09', 'type': 'autocustom'},
  'permissions': {'IVL': {'read': False,
    'create': False,
    'delete': False,
    'update': False}},
  'descriptions': [],
  'solicitation': {'deadlines': {'response': '2019-10-08T23:59:59-04:00',
    'responseTz': 'America/New_York'}},
  'organizationId': '100176853',
  'pointOfContact': [{'type': 'primary',
    'email': 'testy@testy.gov',
    'fullName': 'Name',
    'additionalInfo': {'content': 'Description mail'}}],
  'classificationCode': 'testy',
  'placeOfPerformance': {'zip': '20170',
   'country': {'code': 'USA', 'name': 'UNITED STATES'},
   'streetAddress': 'Alton Sq'},
  'solicitationNumber': 'testy',
  'additionalReporting': ['none'],
  'organizationLocationId': '50175943'},
 'additionalInfo': {'sections': [{'id': 'header', 'status': 'updated'},
   {'id': 'award', 'status': 'updated'},
   {'id': 'general', 'status': 'updated'},
   {'id': 'classification', 'status': 'updated'},
   {'id': 'description', 'status': 'updated'},
   {'id': 'attachments-links', 'status': 'updated'},
   {'id': 'contact', 'status': 'updated'}]},
 'parent': {},
 'related': {},
 'status': {'code': 'published', 'value': 'Published'},
 'archived': False,
 'cancelled': False,
 'latest': True,
 'deleted': False,
 'postedDate': '2019-09-25T21:43:03.675+0000',
 'modifiedDate': 'modDate',
 'createdDate': '2019-09-25T21:42:23.210+0000',
 'modifiedBy': '',
 'createdBy': '',
 'opportunityId': 'testy'}

mock_opps = [mock_opp_one, mock_opp_two]

mock_data = {'_embedded': {'results': mock_opps}}

mock_schematized_opp_one = {'notice type': 'test', 'solnbr': 'test', 'agency': 'agency', 'compliant': 0, 'office': 'office', 'opp_id': 'test', 'attachments': [], 'classcod': 'test', 'naics': 'test', 'subject': 'test', 'url': 'https://beta.sam.gov/opp/123/view', 'setaside': 'test', 'emails': ['test@test.gov']}

mock_attachment_data = {'text': 'test', 'filename': 'test.txt', 'machine_readable': True, 'url': 'test', 'prediction': None, 'decision_boundary': None, 'validation': None, 'trained': False}

mock_transformed_opp_one = {'notice type': 'test', 'solnbr': 'test', 'agency': 'agency', 'compliant': 0, 'office': 'office', 'attachments': [mock_attachment_data], 'classcod': 'test', 'naics': 'test', 'subject': 'test', 'url': 'https://beta.sam.gov/opp/123/view', 'setaside': 'test', 'emails': ['test@test.gov']}

mock_data_for_db = {'notice type': 'Presolicitation', 'solnbr': 'test', 'agency': 'agency', 'compliant': 0, 'office': 'office', 'attachments': [mock_attachment_data], 'classcod': 'test', 'naics': 'test', 'subject': 'test', 'url': 'url', 'setaside': 'test', 'emails': ['test@test.gov']}