name: SRT-FBO-Scraper DEV Deploy

on:
    push:
      branches:
        - 'dev'

        jobs:
            docker:
              name: Build and Push Docker Image
              runs-on: ubuntu-latest
              outputs:
                formattedTime: ${{ steps.current-time.outputs.formattedTime }}
              steps:
                - 
                  name: Get Current Time
                  uses: josStorer/get-current-time@v2.1.1
                  id: current-time
                  with:
                    format: YYYYMMDD-HHmmss
                -
                  name: Set up QEMU
                  uses: docker/setup-qemu-action@v2
                -
                  name: Set up Docker Buildx
                  uses: docker/setup-buildx-action@v2
                  with:
                    version: v0.9.1
                - 
                  name: Login to Docker Hub
                  uses: docker/login-action@v2
                  with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
                -
                  name: Build and push
                  uses: docker/build-push-action@v4
                  with:
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/srt-fbo-scraper:dev-${{ steps.current-time.outputs.formattedTime }}
            
            cloudgov:
              name: Deploying to Cloud.gov
              runs-on: ubuntu-latest
              needs: docker
              steps:
                -
                  name: Checkout
                  uses: actions/checkout@v3.5.3
                - 
                  name: Check Working Directory
                  run: |
                    ls -la
                -
                  name: Push to Cloud.gov Dev Space
                  uses: citizen-of-planet-earth/cf-cli-action@master
                  with:
                    cf_api: https://api.fr.cloud.gov
                    cf_username: ${{ secrets.CF_USER }}
                    cf_password: ${{ secrets.CF_PASSWORD }}
                    cf_org: gsa-ogp-srt
                    cf_space: dev
                    command: push srt-fbo-scraper-dev -f cf/manifest.dev.yml --docker-image ${{ secrets.DOCKERHUB_USERNAME }}/srt-fbo-scraper:dev-${{ needs.docker.outputs.formattedTime }}
          